// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvs4VTkwPaqhMCwwhM0VejfGQUWhTnww4',
    appId: '1:591038085254:web:7dab973357cfb8c9867907',
    messagingSenderId: '591038085254',
    projectId: 'rentapp-daril',
    authDomain: 'rentapp-daril.firebaseapp.com',
    storageBucket: 'rentapp-daril.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArtsogZtkAwDrIFtMQSv1TwK29vkkDaco',
    appId: '1:591038085254:android:ca932a9ebea05fd9867907',
    messagingSenderId: '591038085254',
    projectId: 'rentapp-daril',
    storageBucket: 'rentapp-daril.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAYwojigYKN_CQdH_dhfpp8gj11f0h_M4',
    appId: '1:591038085254:ios:ca08da1c44fc0c8f867907',
    messagingSenderId: '591038085254',
    projectId: 'rentapp-daril',
    storageBucket: 'rentapp-daril.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAYwojigYKN_CQdH_dhfpp8gj11f0h_M4',
    appId: '1:591038085254:ios:ca08da1c44fc0c8f867907',
    messagingSenderId: '591038085254',
    projectId: 'rentapp-daril',
    storageBucket: 'rentapp-daril.firebasestorage.app',
    iosBundleId: 'com.example.rentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvs4VTkwPaqhMCwwhM0VejfGQUWhTnww4',
    appId: '1:591038085254:web:61cc3b5c28f7c3d8867907',
    messagingSenderId: '591038085254',
    projectId: 'rentapp-daril',
    authDomain: 'rentapp-daril.firebaseapp.com',
    storageBucket: 'rentapp-daril.firebasestorage.app',
  );

}